# Generated by Django 3.0.6 on 2020-05-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luminosity', '0003_auto_20200513_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='luminosity',
            old_name='tipo',
            new_name='Tipo',
        ),
        migrations.RenameField(
            model_name='luminosity',
            old_name='value',
            new_name='Valor',
        ),
    ]
