# Generated by Django 3.0.6 on 2020-05-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminosity', '0004_auto_20200513_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luminosity',
            name='latitud',
            field=models.IntegerField(verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='luminosity',
            name='longitud',
            field=models.IntegerField(verbose_name='longitud'),
        ),
    ]
